name: Build Flutter Desktop Apps

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Package Windows build
        run: |
          cd build/windows/runner/Release
          powershell Compress-Archive * ../../../FocusTracker-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/FocusTracker-windows.zip


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --release

      - name: Package macOS app
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../FocusTracker-macos.zip *.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/FocusTracker-macos.zip


  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            FocusTracker-windows.zip
            FocusTracker-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}